"""runtime_settings

Revision ID: 30f8c851da27
Revises: 5d20a0acbb5f
Create Date: 2026-07-12 02:12:18.763116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '30f8c851da27'
down_revision: Union[str, None] = '5d20a0acbb5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('runtime_settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('runtime_settings')
    # ### end Alembic commands ###
