"""users.avatar

Revision ID: 5d20a0acbb5f
Revises: 753b4793e3ac
Create Date: 2026-07-11 21:51:16.926473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5d20a0acbb5f'
down_revision: Union[str, None] = '753b4793e3ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar', sa.LargeBinary(), nullable=True))
    op.add_column('users', sa.Column('avatar_mime', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_mime')
    op.drop_column('users', 'avatar')
    # ### end Alembic commands ###
