"""rounds.top3

Revision ID: 753b4793e3ac
Revises: e6d60a978b13
Create Date: 2026-07-11 21:17:00.607533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '753b4793e3ac'
down_revision: Union[str, None] = 'e6d60a978b13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rounds', sa.Column('top3', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rounds', 'top3')
    # ### end Alembic commands ###
