"""moderator fields

Revision ID: d60a33aa2a01
Revises: 30f8c851da27
Create Date: 2026-07-12 12:10:50.098520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd60a33aa2a01'
down_revision: Union[str, None] = '30f8c851da27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_moderator', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('users', sa.Column('banned_until', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'banned_until')
    op.drop_column('users', 'is_moderator')
    # ### end Alembic commands ###
